### ISSUE TITLE
Gesture feature: unable to move camera vertically 

### ISSUE THREAD

**Issue by aaronliew** [googlevr/gvr-android-sdk#196]
Hi, 

Device: Samsung s6
Android version : 6.0.1

I'm able to move the camera horizontally via gesture. However, I couldn't move the camera vertically in full screen mode. Can you please advice me on the way to solve this issue ? Thanks!

**Comment by ariviere** [comment]
I couldn't get it to work too. 

I've seen in the TouchTracker class that there is a "verticalTrackingEnabled" boolean but even in fullscreen (where it's supposed to be enabled), it's not scrolling vertically.

Vertical scrolling is an important feature in the project I'm working on :(

**Comment by nathanmartz** [comment]
Which version of the SDK are you using? I thought we'd fixed this for the 1.0 release.

**Comment by ariviere** [comment]
I'm using the latest version of the SDK (1.0.0) with the "simplevideowidget" sample and a HLS file since I cannot get the file "congo.mp4" to play. I click on the fullscreen button and when I try to scroll vertically, nothing happens.

Also, is it possible to get an option to activate the vertical scrolling even when we're not in fullscreen ?

**Comment by nathanmartz** [comment]
Thanks for the info. We'll address this info in a future update.

**Comment by DCarretero59** [comment]
Any update on this issue?? Been trying to solve this for a while

**Comment by ariviere** [comment]
Up! 

Did anyone found a workaround for this issue while we wait for an official fix ? I tried to extend classes from the library but too many methods and attributes are private :(

**Comment by LandChanning** [comment]
I got the same trouble, hope this problem will be solved soon.

**Comment by p-fischer** [comment]
I also need to enable vertical scrolling via gestures.
Even when I'm setting "verticalTrackingEnabled" to true it works in neither fullscreen nor non-fullscreen mode.

**Comment by p-fischer** [comment]
I did some debugging:
In fullscreen mode, the flag "verticalTrackingEnabled" (see VrWidgetView) is set to true. The onTouchListener (see TouchTracker) recognizes movement on both x- and y-axis. Finally, VrWidgetRenderer calls method nativeOnPanningEvent with dx and dy having values other than 0. This is where I lost track. Sadly, it seems, this issue can only been fixed in native code.

**Comment by DCarretero59** [comment]
Does anyone know if it has been fixed in the 1.20 update? Gonna try another way if it's not unfortunately.

**Comment by ariviere** [comment]
According to the release note, it's not fixed https://developers.google.com/vr/android/release-notes

But I haven't tried it yet

**Comment by DCarretero59** [comment]
It's not unfortunately

**Comment by isagorr** [comment]
It's not yet fixed in 1.30 either.

**Comment by SMikhlevskiy** [comment]
I do not have a gyro on my phone. Without vertical scrolling , the widget looks terrible. Will the bug fix in the near future or should I look for another library?

**Comment by p-fischer** [comment]
Has anyone found a workaround / hack to enable vertical scrolling?

@nathanmartz Can you give us some status update please?

**Comment by isagorr** [comment]
This is one of the most commented issues, and yet did not get fixed with the new 1.60 release :(

Whereas there is a new feature setPureTouchTracking(); vertical tracking actually works if this is set (but no gyro obviously). Not fair :P

**Comment by p-fischer** [comment]
I updated to version `1.60.0` and tried that new method `setPureTouchTracking()` however that leads to an immediate app crash producing the following stack trace:
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.nativeSetPureTouchTracking(long, boolean) (tried Java_com_google_vr_sdk_widgets_pano_VrPanoramaRenderer_nativeSetPureTouchTracking and Java_com_google_vr_sdk_widgets_pano_VrPanoramaRenderer_nativeSetPureTouchTracking__JZ)
  at com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.nativeSetPureTouchTracking(Native Method)
  at com.google.vr.sdk.widgets.common.VrWidgetRenderer$SetPureTouchTrackingRequest.execute(VrWidgetRenderer.java:322)
  at com.google.vr.sdk.widgets.common.VrWidgetRenderer.executeApiRequestOnGlThread(VrWidgetRenderer.java:257)
  at com.google.vr.sdk.widgets.common.VrWidgetRenderer.onSurfaceCreated(VrWidgetRenderer.java:120)
  at com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.onSurfaceCreated(VrPanoramaRenderer.java:63)
  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```
@isagorr did you run into the same issue?

**Comment by isagorr** [comment]
@p-fischer I just tried it and yes, it crashes. Works with VrVideoView though.

**Comment by p-fischer** [comment]
I opened a new issue for that problem #434

**Comment by p-fischer** [comment]
I tested this again with version `1.80.0` and "pure touch tracking" mode is now implemented for `VrPanoramaView` :)

Summed up: vertical camara movements through gestures work now. Just not in the hybrid way together with gyroscope navigation, but as a separate mode.

In general, I would really appreciate version change logs and if the GitHub issues would be updated with that kind of information by the maintainers of the library.

**Comment by iNicod** [comment]
I've used the function setPureTouchTracking(true); it works well but it disable the gyroscope do you know why ? can we keep both gesture and gyroscope enabled ?

**Comment by jdduke** [comment]
Thanks for the confirmation @p-fischer.

@iNicod, at the moment we don't have any plans to support simultaneous gyro + touch tracking, but we'll consider it for the future.

**Comment by sigmaxipi** [comment]
If you want a more complex touch & gyro controls for a 360 media player, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.

**Comment by Gervil** [comment]
The solution for this is only set this setPureTouchTracking(true);

**Comment by savadmv** [comment]
The following code works for me

 panoWidgetView.setPureTouchTracking(true);
