### ISSUE TITLE
Avoid Google VR service Warning for nonDaydream devices?

### ISSUE THREAD

**Issue by ChrisCW1** [googlevr/gvr-android-sdk#362]
Hi folks.

After Android 7 update i got this "Warning: ... Please install Google VR services..." message on my S7 everytime i access the VrVideoView widget.
The problem is - there are no Google VR services for this device so i will get this kind of warning every time i access content that was build using Google VR SDK?

<img src="https://i.stack.imgur.com/GWucD.png" /> 

See: http://stackoverflow.com/questions/42022329/avoid-warning-after-android-7-update-for-nondaydream-devices

Thanks

**Comment by jdduke** [comment]
Hi @ChrisCW1 , are you using the latest version of the GVR SDK?

**Comment by jdduke** [comment]
We're looking into this, thanks for the report.

**Comment by ChrisCW1** [comment]
Hi @jdduke,

yes - same with the latest relase / i tried the sample app (SimpleVrVideoActivity)... 

Side By Side view (tap on cardboard icon) is not possible anymore because of this Warning!
The warning appears in background and the player stops and you cant resume - because of the mentioned Warning that waits for your input in background.

**Comment by ChrisCW1** [comment]
![screenshot_20170206-112802](https://cloud.githubusercontent.com/assets/16015592/22643785/47829b10-ec60-11e6-9fc1-1136b581ec03.png)

**Comment by GuyAglionby** [comment]
Any update on this issue? Same device, using the latest version of the SDK.

**Comment by Cooper6334** [comment]
Same issue. 
This dialog shows every time when I press the x button at the left top corner on VrVideoView.
I'm using HTC M9 with Android 7.0 and Google VR SDK 1.10.0

**Comment by jdduke** [comment]
Apologies for the delayed response.

The issue here is that these devices are shipping with VR mode support, but don't actually ship with Google VR Services installed on the system image. We'll soon be releasing Google VR Services to *all* devices that have Android N, not just Daydream-ready devices, at which point users will be able to download and install the app and continue using VR.

We'll also be updating the next SDK release to suppress this warning dialog for VrVideoView.  I'll close this bug when both Google VR Services is universally available and we've released the updated SDK. Thanks for your patience.

**Comment by achuvm** [comment]
Hi @jdduke 

We just ran into this issue today with our product (our S7 just got its Nougat update).

Is there an ETA as to when that change to the Google VR Service will go out?

Thanks,

**Comment by jdduke** [comment]
Google VR Services is now available for all Android N devices, so your users should have no issues downloading and installing it. We've also updated the widgets to avoid triggering the dialog when Google VR Services is unavailable.

**Comment by kesefworld** [comment]
Hi, I am building vr games and I also have this problem.  I have  (as far as I know) the latest google VR sdk version 1.30. To test my apk I build and run it to my galaxy s7 edge and when I run the game that google warning comes up. Like I said I'm using the latest sdk version so why am I still seeing this warning message? Thanks in advance.

**Comment by achuvm** [comment]
Hi Kesef, you need to open the Play Store, find the Google VR Services app and install it.
![screenshot_20170417-183241](https://cloud.githubusercontent.com/assets/21074927/25110909/60e565ce-239c-11e7-95e0-25231c6de9ea.png)

**Comment by kesefworld** [comment]
Thanks for the response but I actually have it uploaded to the phone for about a month now but I still get the warning.

**Comment by Leifzhang** [comment]
I  try  the version  1.40.  already fix it
