### ISSUE TITLE
Increase in VSync misses in Google VR Services update 1.10.170928015

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-android-sdk#482]
During testing of a Pixel XL (Android 8) and Moto Z (Android 7.1.1) I've been noticing many more VMiss in the Daydream Performance HUD when using VR Services version 1.10.170928015 and 1.10.170249286. When the HUD is disabled I can visually detect the frame drop, breaking Async Reprojection and causing discomfort while viewing. The drops happen during a high CPU / IO period of my app, but it is objectively worse than the earlier 1.8.163477258 VR Services.

Potentially somewhat related, I notice the GVR Frame NAF graph visually looks different in these two versions (note these screenshots are not of the vsync issue, they're essentially at idle):

Version 1.10.170928015
![screenshot_20171010-143602](https://user-images.githubusercontent.com/7659306/31403992-cd4c9e74-adc8-11e7-9bb0-9f7b1c1a5ff9.png)

Version 1.8.163477258
![screenshot_20171010-143740](https://user-images.githubusercontent.com/7659306/31403993-cd5c63e0-adc8-11e7-8e48-2226cbd2e65e.png)

Has anyone seen similar behavior?

PS - I know this is more the Android GVR SDK repo, but I wasn't quite sure where to actually file this bug.

**Comment by jdduke** [comment]
Hi @dustinkerstein, can you provide any more details about repro conditions? Are you using the GVR SDK directly, or an engine (Unreal/Unity)? It would also help if you could attach or send a bug report which captures the problem (adb bugreport missed_frames.zip). Also, is the dropped frame behave similar between the Pixel XL and the Moto Z, or are there differences? Thanks.

**Comment by dustinkerstein** [comment]
Hey @jdduke, I'm using Unity 2017.1.1p1 which I believe is based on the GVR 1.80 NDK. 

Below are two bug reports, one from 1.8.163477258 which was taken during an app run which didn't show any vsync misses and another from 1.10.170928015 which was taken during the same app/scene but had around 4-5 vsync misses.

[missed_frames1.8.163477258.zip](https://github.com/googlevr/gvr-android-sdk/files/1375705/missed_frames1.8.163477258.zip)

[missed_frames1.10.170928015.zip](https://github.com/googlevr/gvr-android-sdk/files/1375704/missed_frames1.10.170928015.zip)

The vsync miss behavior appears to be the same for both the Moto Z and Pixel XL.  While there aren't many misses (usually around 4-10 during the high CPU / IO period), the older VR services has a consistent 0 misses during that same period over many tests.

I've also seen more vsync misses in other Daydream apps, and even in the Daydream Home application.

Let me know if there's anything else I can help debug.

**Comment by dustinkerstein** [comment]
@jdduke Let me know if you'd to have the APK that I am testing with.

**Comment by jdduke** [comment]
@dustinkerstein: That would actually be very helpful. Feel free to email me directly if you prefer not to attach. Thanks.

**Comment by dustinkerstein** [comment]
Sure thing. Check your email.

**Comment by davidcox70** [comment]
I was wondering if there is an update on this issue? I started to encounter "sticky" head tracking with an ongoing Unity / Google DayDream app project, tested on a Galaxy S8.  I further found that the DayDream home environment similarly suffered from "sticky" head tracking where it hadn't done so previously. 

I found that if I uninstalled all updates from Google VR Services (1.10.172754103), which dropped it back to version 1.6x, motion smoothness returned in my app, albeit now incompatible with DayDream due to the roll back.

Am I correct to be waiting for a fix for Google VR Services or is there something I have missed?
Thanks for your help.
DC

**Comment by jdduke** [comment]
Hi @davidcox70, would you mind filing a separate bug, describing your symptoms, the Android version on the device, the exact device model (there are many S8 flavors)? Preferably with a bug report that has the "enable performance monitoring" option enabled from the developer settings on Google VR Services (you can activate developer options by tapping the Build version icon from the settings menu 7 times). Thanks.

**Comment by dustinkerstein** [comment]
@jdduke, David's description of the behavior sounds like the behavior I see. It's just that I was looking at the HUD to confirm why I was seeing those frame drops. If I disable the HUD, the "discomfort" that I mentioned above manifests as the "sticky" head when it's particularly bad (more than 1-2 frame drops). Sometimes it's more minor and only results in single frame drop flicker.

**Comment by jdduke** [comment]
Right, I'm not disputing that the symptoms appear similar. Howeer, the S8 can have very different performance profiles depending on the model (Mali vs Qualcomm).

Also, @davidcox70, when you say "sticky" head tracking, is it just a single frame that is being dropped? Or multiple frames? How frequently does this occur in Daydream home?

**Comment by davidcox70** [comment]
Hi Guys - thanks for the responses.

The symptoms are that as you turn your head, the motion is not smooth because an occasional single frame does not seem to be rendered correctly with regard to the viewing angle. It feels like the view has jumped to a slightly different angle for a single frame, causing a momentary break in the smooth motion. I suspect what I am seeing is a frame rendered out of sequence. Imagine watching a sequence that went frame 1,2,3,4,3,6,7. I come to this suspicious because if I move my head left/right, the "jump" is horizontal. If I move my head up down, the jump is vertical. No jumps are apparent in a static scene without head motion.

The frequency of this anomaly is that a frame will be "dropped" between every couple of seconds, through to several times a second. It is commonplace to see it from the start.

I have noticed the symptoms in an app I am developing in Unity, but also the Day Dream home environment and even the "blue mountain-scape" initial Day Dream scene.

Additionally, there are much less frequent occurrences where the head tracking appears to freeze for up to 1/2 second (although usually for less time). At such times, the scene rotates with the head movement (i.e. the scene is locked to the head turn without a viewing angle change).

These behaviours seems to have been introduced in the last couple of weeks as I did not experience any problems prior. I note that Google VR Services was updated on October 19th, so perhaps this is relevant. As I mentioned, uninstalling all updates for Google VR Services, which drops it back to version 1.6x, does allow my app to run smoothly.

My test device is a Samsung Galaxy S8 Model SM-G950F
Android Version 7.0
Kernel 4.4.13-12050265
Daydream version 1.10.170912063
Google VR Services Version: 1.10.172754103

Thanks for your thoughts about this.

DC

**Comment by sigmaxipi** [comment]
@davidcox70, we're investigating this issue. Did you start seeing this on Nov 1st? We think it's caused by a change on that date rather than a recent build of GVR Services. Can you verify using the [Performance HUD](https://developers.google.com/vr/tools/perfhud) similar to @dustinkerstein? This issue manifests as a VMiss events happening even when the app is consistently rendering at 60fps. So launching the Daydream Home app and waiting for everything to settle will show 60fps on the graph but the screen will be flashing red due to the VMisses.

@dustinkerstein the issue you're seeing is different from @davidcox70 who is seeing an issue that started manifesting on Exynos S8 devices on Nov 1st.

**Comment by dustinkerstein** [comment]
@sigmaxipi Do you mean the beta Android 8.0 Oreo update for the S8? Though @davidcox70 appears to be running Android 7.0 and also did mention his issue seems to go away when he reverts to the older Google VR Services - which is also the behavior I see on my Moto Z (Android 7) and Pixel XL (Android 8).

**Comment by sigmaxipi** [comment]
@dustinkerstein The issue was caused by a configuration change that happened on November 1st. It's not a new apk. We're working on updating the configuration so the VMiss issue should go away once the new configuration propagates. You can wait 24 hours or try speeding this up by clearing data for GVR Services.

**Comment by davidcox70** [comment]
@sigmaxipi  Thanks for investigating. I can confirm that when the performance HUD is enabled, the "flash" frames are replaced by red frames (and corresponding lines on the time display), indicating that they are indeed the result of VMisses.

I *thought* I started to see it before 1st November, but I could be wrong. I was in a period of completing a game and seeing how far I could push additional graphics before it caused performance issues, so perhaps any earlier issues were self-induced.

**Comment by markqvist** [comment]
I'm a thinking that this started before november 1st as well. I remember I first noticed it in a WebVR photo viewer I'm working on, but shrugged it off for a while, since I figured it was just something local on the phone I was testing with. It wasn't until a few days ago that I noticed the issue was present on all Exynos S8 devices I had.

Having just cleared the data for Google VR Services seems to have helped in some apps, and the home screen, but not all. Chrome in VR is for example still exhibiting the issue very heavily.

**Comment by dustinkerstein** [comment]
@sigmaxipi Does the new configuration change only apply to Exynos-based Daydream phones? Or is it possible this could also affect Qualcomm devices? If it's only the Exynos chipset, then maybe we should create a specific ticket for that, since this original ticket is sounding like a different underlying issue but just happens to manifest the same behavior.

Also, would you be able to provide any details on what the Exynos configuration change actually is? I'm just curious. Thanks.

**Comment by diegobez** [comment]
Having the same issues. A Samsung Exynos s8, performance monitoring on, and a lot of vsync misses at Daydream Home. ( lots of red stripes ).

**Comment by benvrakas** [comment]
as of today the problem persists exactly as described. i am able to get smooth performance on older versions of GVR, but with the currently avalabe dsfsfsfsfsf

**Comment by jdduke** [comment]
Those of you observing the issue on the S8 exynos, if you could capture a bug report and forward to me (let me know if you'd prefer a reply from a google.com alias), that would be very helpful.

**Comment by benvrakas** [comment]
@jdduke I have done as you asked.

**Comment by xxXFalvorSaviorXxx** [comment]
Same issue on my Galaxy Note 8 (Exynos variant).
Daydream is literally unusable because of this because the jittering causes severe discomfort.

**Comment by jdduke** [comment]
Thanks for the reports, we've finally been able to repro the issue on our end. I'll report back as details emerge. And thanks for your patience.

**Comment by jdduke** [comment]
Hey all, yesterday we pushed an update rendering configuration for Exynos-based S8 devices. That should alleviate the periodic frame drops seen on these devices. Please confirm whether you notice an improvement. Note that you might need to restart your device (or at the very least, kill your application process completely) for the new configuration to take effect. I should also note that you'll need the latest version of Google VR Services.

**Comment by xxXFalvorSaviorXxx** [comment]
@jdduke Can confirm, its fixed on my Galaxy S8 and Note 8 Exynos. Runs totally fine now!

**Comment by jdduke** [comment]
Yes, some apps that are heavy might still exhibit the occasional stutter, but there should be at least some slack affordance now for hitting vsync. Thanks all for your patience.

**Comment by gtaadicto** [comment]
I still have the jitter and a lot of missed frames on my exynos note8 on android 7.1.1.
The daydream version is 1.13.180130063 and google vr services 1.13.185188193
Altspace VR and Chrome WebVR are still unusable.
